---
kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    type: local-storage
    app: jenkins
    role: docker
  name: docker-pv
  namespace: jenkins
spec:
  capacity:
    storage: 2500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /datadrive/docker
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - "worker"
  persistentVolumeReclaimPolicy: Retain
