---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarqube
  name: sonarqube-conf-pvc
  namespace: jenkins
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2500Mi
  selector: 
    matchLabels:
      role: sonarqube-conf
