- name: Check manifests exist
  stat:
    path: "/home/{{ admin }}/k8s/jenkins"
  register: manifests

- name: Check if Jenkins data share exists
  stat:
    path: "/datadrive/export/jenkins-data"
  register: jenkins_data

- name: Check if Sonarqube conf share exists
  stat:
    path: "/datadrive/export/sonarqube/conf"
  register: sonar_conf

- name: Check if Sonarqube data share exists
  stat:
    path: "/datadrive/export/sonarqube/data"
  register: sonar_data

- name: Check if Sonarqube logs share exists
  stat:
    path: "/datadrive/export/sonarqube/logs"
  register: sonar_logs

- name: Check if Docker share exists
  stat:
    path: "/datadrive/export/root/docker"
  register: docker_root

- name: Check if Jenkins namespace exists
  shell: kubectl get ns jenkins
  register: jenkins_ns_status
  ignore_errors: true

- name: Check if Docker Daemon configmap exists
  shell: kubectl -n jenkins get configmap docker-daemon
  register: docker_daemon_status
  ignore_errors: true

- name: Check if jenkins pv exists
  shell: kubectl -n jenkins get pv jenkins-pv
  register: jenkins_pv_status
  ignore_errors: true

- name: Check if jenkins pvc exists
  shell: kubectl -n jenkins get pvc jenkins-pvc
  register: jenkins_pvc_status
  ignore_errors: true

- name: Check if Sonarqube data pv exists
  shell: kubectl -n jenkins get pv sonarqube-data-pv
  register: sonarqube_data_pv_status
  ignore_errors: true

- name: Check if Sonarqube data pvc exists
  shell: kubectl -n jenkins get pvc sonarqube-data-pvc
  register: sonarqube_data_pvc_status
  ignore_errors: true

- name: Check if Sonarqube conf pv exists
  shell: kubectl -n jenkins get pv sonarqube-conf-pv
  register: sonarqube_conf_pv_status
  ignore_errors: true

- name: Check if Sonarqube conf pvc exists
  shell: kubectl -n jenkins get pvc sonarqube-conf-pvc
  register: sonarqube_conf_pvc_status
  ignore_errors: true

- name: Check if Sonarqube logs pv exists
  shell: kubectl -n jenkins get pv sonarqube-logs-pv
  register: sonarqube_logs_pv_status
  ignore_errors: true

- name: Check if Sonarqube logs pvc exists
  shell: kubectl -n jenkins get pvc sonarqube-logs-pvc
  register: sonarqube_logs_pvc_status
  ignore_errors: true

- name: Check if docker pv exists
  shell: kubectl -n jenkins get pv docker-pv
  register: docker_pv_status
  ignore_errors: true

- name: Check if jenkins pvc exists
  shell: kubectl -n jenkins get pvc docker-pvc
  register: docker_pvc_status
  ignore_errors: true

- name: Is Jenkins running?
  shell: kubectl -n jenkins get deploy jenkins-deployment
  register: jenkins_pod_status
  ignore_errors: true

- name: Is Sonarqube running?
  shell: kubectl -n jenkins get deploy sonarqube-deployment
  register: sonarqube_pod_status
  ignore_errors: true

- name: Is Jenkins primary service defined?
  shell: kubectl -n jenkins get svc jenkins-service
  register: jenkins_svc_status
  ignore_errors: true

- name: Is Jenkins JNLP service defined?
  shell: kubectl -n jenkins get svc jenkins-node-service
  register: jenkins_node_svc_status
  ignore_errors: true

- name: Is Sonarqube service defined?
  shell: kubectl -n jenkins get svc sonarqube-service
  register: sonarqube_svc_status
  ignore_errors: true

- name: Is Jenkins Ingress defined?
  shell: kubectl -n jenkins get ing jenkins-ingress
  register: jenkins_ing_status
  ignore_errors: true

- name: Is Sonarqube Ingress defined?
  shell: kubectl -n jenkins get ing sonarqube-ingress
  register: sonarqube_ing_status
  ignore_errors: true
