- name: Apply Jenkins namespace
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/namespace.yaml
    sleep 2
  when: jenkins_ns_status is failed or (force is defined and force | lower == "yes")

- name: Apply Docker config
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/docker-daemon.yaml
    sleep 2
  when: docker_daemon_status is failed or (force is defined and force | lower == "yes")

- name: Apply Jenkins Peristent Volume
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/pv.yaml
    sleep 2
  when: jenkins_pv_status is failed or (force is defined and force | lower == "yes")

- name: Apply Sonarqube conf Peristent Volume
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/sonarqube-conf-pv.yaml
    sleep 2
  when: sonarqube_conf_pv_status is failed or (force is defined and force | lower == "yes")

- name: Apply Sonarqube data Peristent Volume
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/sonarqube-data-pv.yaml
    sleep 2
  when: sonarqube_data_pv_status is failed or (force is defined and force | lower == "yes")

- name: Apply Sonarqube logs Peristent Volume
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/sonarqube-logs-pv.yaml
    sleep 2
  when: sonarqube_logs_pv_status is failed or (force is defined and force | lower == "yes")

- name: Apply Docker Peristent Volume
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/docker-pv.yaml
    sleep 2
  when: docker_pv_status is failed or (force is defined and force | lower == "yes")

- name: Apply Jenkins Peristent Volume Claims
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/pvc.yaml
    sleep 2
  when: jenkins_pvc_status is failed or (force is defined and force | lower == "yes")

- name: Apply Jenkins Peristent Volume Claims
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/sonarqube-conf-pvc.yaml
    sleep 2
  when: sonarqube_conf_pvc_status is failed or (force is defined and force | lower == "yes")

- name: Apply Sonarqube data Peristent Volume Claims
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/sonarqube-data-pvc.yaml
    sleep 2
  when: sonarqube_data_pvc_status is failed or (force is defined and force | lower == "yes")

- name: Apply Sonarqube logs Peristent Volume Claims
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/sonarqube-logs-pvc.yaml
    sleep 2
  when: sonarqube_logs_pvc_status is failed or (force is defined and force | lower == "yes")

- name: Apply Docker Peristent Volume Claims
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/docker-pvc.yaml
    sleep 2
  when: docker_pvc_status is failed or (force is defined and force | lower == "yes")

- name: Apply Jenkins Deployment
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/jenkins-docker.yaml
    sleep 2
  when: jenkins_pod_status is failed or (force is defined and force | lower == "yes")

- name: Apply Sonarqube Deployment
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/sonarqube.yaml
    sleep 2
  when: sonarqube_pod_status is failed or (force is defined and force | lower == "yes")

- name: Apply Jenkins primary Service
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/jenkins-service.yaml
    sleep 2
  when: jenkins_svc_status is failed or (force is defined and force | lower == "yes")

- name: Apply Jenkins JNLP Service
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/jenkins-node-service.yaml
    sleep 2
  when: jenkins_node_svc_status is failed or (force is defined and force | lower == "yes")

- name: Apply Sonarqube Service
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/sonarqube-service.yaml
    sleep 2
  when: sonarqube_svc_status is failed or (force is defined and force | lower == "yes")

- name: Apply Jenkins Ingress
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/jenkins-ingress.yaml
    sleep 2
  when: jenkins_ing_status is failed or (force is defined and force | lower == "yes")

- name: Apply Sonarqube Ingress
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/jenkins/sonarqube-ingress.yaml
    sleep 2
  when: sonarqube_ing_status is failed or (force is defined and force | lower == "yes")
