locals {
  l-manager-1-temp-name   = "${format("%s-%s-MANAGER%s", var.target, var.vm-name, local.l-dev)}"
  l-manager-1-name-1      = "${format("VM-%s-%s-MANAGER-1%s-%s%s", var.target, var.vm-name, local.l-dev, var.environ, local.l-random)}"
  l-manager-1-osdisk-1    = "${format("OSD-%s-%s-MANAGER-1%s-%s%s", var.target, var.vm-name, local.l-dev, var.environ, local.l-random)}"
  l-manager-1-pk-file     = "${format("%s.pub", var.private-key)}"
}

module "vm-manager-1" {
  source                           = "git::https://github.com/dsandersAzure/terraform-library.git//modules/standard-linux-vm-datadisk?ref=0.6.0"
  name                             = "${local.l-manager-1-name-1}"
  location                         = "${var.location}"
  resource-group-name              = "${module.resource-group.name}"
  nic-id                           = "${module.nic-master-1.id}"
  availability-set-id              = "${module.avs-k8s.id}"
  vm-size                          = "${var.manager-vm-size}"
  delete-os-disk-on-termination    = "${var.delete-osdisk-on-termination}"
  delete-data-disks-on-termination = "${var.delete-datadisk-on-termination}"
  primary-blob-endpoint            = "${module.sa-boot-diag.primary_blob_endpoint}"
  image-publisher                  = "Canonical"
  image-offer                      = "UbuntuServer"
  image-sku                        = "18.04-LTS"
  image-version                    = "latest"
  os-disk-name                     = "${local.l-manager-1-osdisk-1}"
  os-disk-create-option            = "FromImage"
  os-disk-caching                  = "ReadWrite"
  os-disk-type                     = "${var.vm-osdisk-type}"
  data-disk-name                   = "${data.azurerm_managed_disk.datasourcemd.name}"
  data-disk-id                     = "${data.azurerm_managed_disk.datasourcemd.id}"
  data-disk-create-option          = "Attach"
  data-disk-lun                    = 0
  data-disk-size                   = "${data.azurerm_managed_disk.datasourcemd.disk_size_gb}"
  adminuser                        = "${var.vm-adminuser}"
  adminpass                        = "${var.vm-adminpass}"
  ssh-key-path                     = "${local.l-manager-1-pk-file}"
  disable-password-auth            = "${var.vm-disable-password-auth}"
  custom-data                      = ""
  tags                             = "${var.tags}"
}
