- name: Apply postgres namespace
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/postgres/namespace.yaml
    sleep 2
  when: postgres_ns_status is failed or (force is defined and force | lower == "yes")

- name: Apply configmap
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/postgres/configmap.yaml
    sleep 2
  when: postgres_config_status is failed or (force is defined and force | lower == "yes")

- name: Apply Peristent Volumes
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/postgres/pv.yaml
    sleep 2
  when: postgres_pv_status is failed or (force is defined and force | lower == "yes")

- name: Apply Peristent Volume Claims
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/postgres/pvc.yaml
    sleep 2
  when: postgres_pvc_status is failed or (force is defined and force | lower == "yes")

- name: Apply Deployments
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/postgres/postgres.yaml
    sleep 2
  when: postgres_deploy_status is failed or (force is defined and force | lower == "yes")

- name: Apply Services
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/postgres/service.yaml
    sleep 2
  when: postgres_svc_status is failed or (force is defined and force | lower == "yes")
