---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sonarqube-ingress
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: "sonarqube{{ domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: sonarqube-service
          servicePort: sonarqube-ui
  tls: # < placing a host in the TLS config will indicate a cert should be created
  - hosts:
    - "sonarqube{{ domain }}"
    secretName: sonarqube-cert # < cert-manager will store the created certificate in this sec
