apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: jenkins
spec:
  ports:
  - name: sonarqube-ui
    protocol: TCP
    port: 9000
    targetPort: 9000
  selector:
    app: sonarqube
