---
kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    type: local-storage
    app: jenkins
    role: sonarqube-logs
  name: sonarqube-logs-pv
  namespace: jenkins
spec:
  capacity:
    storage: 2500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /datadrive/sonarqube/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "role"
          operator: In
          values:
          - "worker"
  persistentVolumeReclaimPolicy: Retain
