- name: Create Docker install location
  file:
    path: /tmp/docker-install
    state: directory
    mode: '0755'
  when: docker.stat.exists == False or (force is defined and force | lower == "yes")

- name: Download and Extract Docker 18.09.6
  unarchive:
    src: https://download.docker.com/linux/static/stable/x86_64/docker-18.09.6.tgz
    dest: /tmp/docker-install/
    remote_src: yes
  when: docker.stat.exists == False or (force is defined and force | lower == "yes")

- name: Download Docker Service
  get_url:
    url: https://raw.githubusercontent.com/moby/moby/master/contrib/init/systemd/docker.service
    dest: /tmp/docker-install/docker.service
  when: docker_service.stat.exists == False or (force is defined and force | lower == "yes")

- name: Download Docker Socket
  get_url:
    url: https://raw.githubusercontent.com/moby/moby/master/contrib/init/systemd/docker.socket
    dest: /tmp/docker-install/docker.socket
  when: docker_socket.stat.exists == False or (force is defined and force | lower == "yes")

- name: Copy Docker binaries
  copy:
    src: "{{ item }}"
    dest: /usr/bin/
    owner: root
    group: root
    mode: '0655'
    remote_src: yes
  with_items:
    - "/tmp/docker-install/docker/containerd"
    - "/tmp/docker-install/docker/containerd-shim"
    - "/tmp/docker-install/docker/ctr"
    - "/tmp/docker-install/docker/docker"
    - "/tmp/docker-install/docker/docker-init"
    - "/tmp/docker-install/docker/docker-proxy"
    - "/tmp/docker-install/docker/dockerd"
    - "/tmp/docker-install/docker/runc"
  when: docker.stat.exists == False or (force is defined and force | lower == "yes")

- name: Copy Docker to /usr/local/bin
  copy:
    src: /tmp/docker-install/docker/docker
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: '0655'
    remote_src: yes
  when: docker_local.stat.exists == False or (force is defined and force | lower == "yes")

- name: Update Docker service to use unix//
  replace:
    path: /tmp/docker-install/docker.service
    regexp: 'dockerd -H fd://'
    replace: 'dockerd -H unix://'
  when: docker_service.stat.exists == False or (force is defined and force | lower == "yes")

- name: Copy Docker Service
  copy:
    src: "/tmp/docker-install/docker.service"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0655'
    remote_src: yes
  when: docker_service.stat.exists == False or (force is defined and force | lower == "yes")

- name: Copy Docker Socket
  copy:
    src: "/tmp/docker-install/docker.socket"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0655'
    remote_src: yes
  when: docker_socket.stat.exists == False or (force is defined and force | lower == "yes")

- name: Make /etc/docker
  file:
    path: /etc/docker
    state: directory
    owner: "root"
  when: docker_etc.stat.exists == False or (force is defined and force | lower == "yes")

- name: Copy daemon.json
  template:
    src: docker_engine/templates/daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
  when: daemon_json.stat.exists == False or (force is defined and force | lower == "yes")
