- name: Create docker group, gid = 10000
  group:
    gid: "10000"
    name: docker
    state: present

- name: Enable Docker services
  systemd:
    name: docker.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: Remove installation media
  file:
    path: /tmp/docker-install
    state: absent
  when: docker.stat.exists == False or (force is defined and force | lower == "yes")
