# -------------------------------------------------------------------
#
# Module:         k8s-terraform
# Submodule:      templates/traefik/6-nginx.yaml
# Environments:   all
# Purpose:        YAML specification to create an nginx sample app
#                 to demo Traefik as an ingress controller.
#
# Created on:     23 June 2019
# Created by:     David Sanders
# Creator email:  dsanderscanada@nospam-gmail.com
#
# -------------------------------------------------------------------
# Modifed On   | Modified By                 | Release Notes
# -------------------------------------------------------------------
# 23 Jun 2019  | David Sanders               | First release.
# -------------------------------------------------------------------
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx-frontend
  name: nginx-frontend
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-frontend
    spec:
      containers:
      - image: nginx:1.16.0-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
