# -------------------------------------------------------------------
#
# Module:         k8s-terraform
# Submodule:      templates/traefik/7-nginx-service.yaml
# Environments:   all
# Purpose:        YAML specification to create a service for the nginx
#                 sample Traefik app.
#
# Created on:     23 June 2019
# Created by:     David Sanders
# Creator email:  dsanderscanada@nospam-gmail.com
#
# -------------------------------------------------------------------
# Modifed On   | Modified By                 | Release Notes
# -------------------------------------------------------------------
# 23 Jun 2019  | David Sanders               | First release.
# -------------------------------------------------------------------
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx-frontend
  ports:
    - protocol: TCP
      port: 80
      name: nginx-http