- name: Check manifests exist
  stat:
    path: "/home/{{ admin }}/k8s/helm"
  register: manifests

- name: Check helm exists
  stat:
    path: "/usr/local/bin/helm"
  register: helm

- name: Check tiller exists
  stat:
    path: "/usr/local/bin/tiller"
  register: tiller

- name: Copy manifest
  copy:
    src: app_helm/manifests/
    dest: "/home/{{ admin }}/k8s/helm"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False

- name: Fetch Helm 2.14.1
  unarchive:
    path: https://get.helm.sh/helm-v2.14.1-linux-amd64.tar.gz
    dest: /tmp/
    remote_src: true
  when: helm.stat.exists == False or tiller.stat.exists == False

- name: Copy Helm
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: '0755'
  when: helm.stat.exists == False

- name: Copy Tiller
  copy:
    src: /tmp/linux-amd64/tiller
    dest: /usr/local/bin/tiller
    mode: '0755'
  when: helm.stat.exists == False

- name: Apply Helm service account
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/helm/service-account.yaml
    sleep 2

- name: Apply Helm cluster role binding
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/helm/cluster-role-binding.yaml
    sleep 2

- name: Install helm
  shell: |
    helm init --service-account {{ helm_service_account_name }} --history-max 200

- name: Remove Helm installation medis
  file:
    path: /tmp/linux-amd64
    state: absent
