apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus-oss-tls
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
  - host: "nexus-tls.dgsd-consulting.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-frontend
          servicePort: nexus-port
  tls: # < placing a host in the TLS config will indicate a cert should be created
  - hosts:
    - nexus-tls.dgsd-consulting.com
    secretName: myingress-cert # < cert-manager will store the created certificate in this sec