apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus-oss
  name: nexus-docker
spec:
  type: NodePort
  ports:
  - name: nexus-docker-port
    port: 18080
    targetPort: 18080
    nodePort: 32080
  - name: nexus-privatehub-port
    port: 18081
    targetPort: 18081
    nodePort: 32081
  - name: nexus-registryhub-port
    port: 18082
    targetPort: 18082
    nodePort: 32082
  - name: nexus-quay-port
    port: 18083
    targetPort: 18083
    nodePort: 32083
  - name: nexus-ms-mcr-port
    port: 18084
    targetPort: 18084
    nodePort: 32084
  selector:
    app: nexus-oss
status:
  loadBalancer: {}
