# -------------------------------------------------------------------
#
# Module:         k8s-terraform
# Submodule:      templates/7-nginx-pvc.yaml
# Environments:   all
# Purpose:        The yaml for the nginx persitent volume claim.
#
# Created on:     27 June 2019
# Created by:     David Sanders
# Creator email:  dsanderscanada@nospam-gmail.com
#
# -------------------------------------------------------------------
# Modifed On   | Modified By                 | Release Notes
# -------------------------------------------------------------------
# 27 Jun 2019  | David Sanders               | First release.
#              |                             | Decomposed larger file.
# -------------------------------------------------------------------
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: nginx-claim0
  name: nginx-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
