# -------------------------------------------------------------------
#
# Module:         k8s-terraform
# Submodule:      templates/6-registry-deploy.yaml
# Environments:   all
# Purpose:        The yaml for the registry deployment.
#
# Created on:     27 June 2019
# Created by:     David Sanders
# Creator email:  dsanderscanada@nospam-gmail.com
#
# -------------------------------------------------------------------
# Modifed On   | Modified By                 | Release Notes
# -------------------------------------------------------------------
# 27 Jun 2019  | David Sanders               | First release.
#              |                             | Decomposed larger file.
# -------------------------------------------------------------------
# 30 Jun 2019  | David Sanders               | Update registry image
#              |                             | to 2.7.1.
# -------------------------------------------------------------------
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: registry
  name: registry
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /data
        image: registry:2.7.1
        name: registry
        ports:
        - containerPort: 5000
          hostIP: 127.0.0.1
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: registry-claim0
      restartPolicy: Always
      volumes:
      - name: registry-claim0
        persistentVolumeClaim:
          claimName: registry-claim0
