# -------------------------------------------------------------------
#
# Module:         k8s-terraform
# Submodule:      templates/4-registry-service.yaml
# Environments:   all
# Purpose:        The yaml for the registry service.
#
# Created on:     27 June 2019
# Created by:     David Sanders
# Creator email:  dsanderscanada@nospam-gmail.com
#
# -------------------------------------------------------------------
# Modifed On   | Modified By                 | Release Notes
# -------------------------------------------------------------------
# 27 Jun 2019  | David Sanders               | First release.
#              |                             | Decomposed larger file.
# -------------------------------------------------------------------
# 27 Jun 2019  | David Sanders               | Update naming stds.
# -------------------------------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry-backend
  name: registry-backend
spec:
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 32000
  selector:
    app: registry-backend
status:
  loadBalancer: {}