- hosts: workers
  become: true
  tasks:
    - import_role:
        name: k8s_workers
      tags: k8s_workers
- hosts: master
  become: true
  tasks:
    - import_role:
        name: k8s_workers_check
      tags: k8s_workers_check
- hosts: workers
  become: true
  tasks:
    - import_role:
        name: k8s_workers_reboot
      tags: k8s_workers_reboot
