- name: Make manifests folder
  file:
    path: "/home/{{ admin }}/k8s/anchore"
    state: directory
    owner: "{{ admin }}"
  when: manifests.stat.exists == False

- name: Copy templated k8s-values.yaml
  template:
    src: app_anchore/templates/k8s-values.yaml.j2
    dest: "/home/{{ admin }}/k8s/anchore/k8s-values.yaml"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False or (force is defined and force | lower == "yes")
