# -------------------------------------------------------------------
#
# Module:         k8s-terraform
# Submodule:      templates/nexus-oss/10-nexus-data-pv.yaml
# Environments:   all
# Purpose:        The persistent volume for /nexus-data
#
# Created on:     15 July 2019
# Created by:     David Sanders
# Creator email:  dsanderscanada@nospam-gmail.com
#
# -------------------------------------------------------------------
# Modifed On   | Modified By                 | Release Notes
# -------------------------------------------------------------------
# 15 Jul 2019  | David Sanders               | First release.
# -------------------------------------------------------------------
---
kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    type: local-storage
  name: nexus-data-pv
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: "/datadrive/nexus-oss/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
         - key: node-role.kubernetes.io/master
           operator: DoesNotExist
  persistentVolumeReclaimPolicy: Retain
