# -------------------------------------------------------------------
#
# Module:         k8s-terraform
# Submodule:      templates/nexus-oss/30-nexus-user-root-pv.yaml
# Environments:   all
# Purpose:        The persistent volume for /user-root
#
# Created on:     15 July 2019
# Created by:     David Sanders
# Creator email:  dsanderscanada@nospam-gmail.com
#
# -------------------------------------------------------------------
# Modifed On   | Modified By                 | Release Notes
# -------------------------------------------------------------------
# 15 Jul 2019  | David Sanders               | First release.
# -------------------------------------------------------------------
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local-storage
  name: nexus-user-root-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Mi
  storageClassName: local-storage
  local:
    path: "/datadrive/nexus-oss/user-root"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
         - key: node-role.kubernetes.io/master
           operator: DoesNotExist
  persistentVolumeReclaimPolicy: Retain
