---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/auth-type: "basic"
    traefik.ingress.kubernetes.io/auth-secret: "traefik-auth"
  name: traefik-web-ui
  namespace: kube-system
spec:
  rules:
  - host: "traefik{{ domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik-web-ui
          servicePort: web
  # tls:
  #  - secretName: traefik-ui-tls-cert