---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local-storage
    role: nexus-blobs
  name: nexus-blob-store-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: local-storage
  local:
    path: "/datadrive/nexus-oss/blobs"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
         - key: role
           operator: In
           values:
           - "worker"
        # - key: node-role.kubernetes.io/master
        #    operator: DoesNotExist
  persistentVolumeReclaimPolicy: Retain
