---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: nexus-data-claim
  name: nexus-data-claim
spec:
  storageClassName: local-storage
  selector: 
    matchLabels:
      role: nexus-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi