apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus-oss-tls
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    certmanager.k8s.io/issuer: "letsencrypt-staging"
spec:
  rules:
  - host: "nexus-tls{{ domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-frontend
          servicePort: nexus-port
  tls: # < placing a host in the TLS config will indicate a cert should be created
  - hosts:
    - "{{ domain }}"
    secretName: nexus-tls-cert # < cert-manager will store the created certificate in this sec