apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus-oss
spec:
  rules:
  - host: "nexus{{ domain_name }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-frontend
          servicePort: nexus-port
