apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus-frontend
  name: nexus-frontend
spec:
  ports:
  - name: nexus-port
    port: 80
    targetPort: 8081
  selector:
    app: nexus-oss
status:
  loadBalancer: {}
