---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local-storage
    role: nexus-user-root
  name: nexus-user-root-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Mi
  storageClassName: local-storage
  local:
    path: "/datadrive/nexus-oss/user-root"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - "worker"
  persistentVolumeReclaimPolicy: Retain
