---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: nexus-user-root-claim
  name: nexus-user-root-claim
spec:
  storageClassName: local-storage
  selector: 
    matchLabels:
      role: nexus-user-root
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi