- name: Check node status
  uri: 
    url: http://localhost:10248/healthz
  ignore_errors: yes
  register: node_status

- name: Join the cluster
  shell: "{{ hostvars['k8s-master']['JOIN_COMMAND'].stdout }}"
  when: node_status is failed
