- name: Check node status
  uri: 
    url: http://localhost:10248/healthz
  ignore_errors: yes
  register: node_status

- name: Join the cluster
  shell: "{{ hostvars['k8s-master']['JOIN_COMMAND'].stdout }}"
  when: node_status is failed

- name: Sleep for 30s to enable workers to ready
  pause:
    seconds: 30

- name: Label worker nodes
  shell: |
    kubectl label node {{ worker_1 }} role=worker
    kubectl label node {{ worker_2 }} role=worker
