- name: Check if Nexus OSS NFS Share exists
  stat:
    path: "/datadrive/export/nexus-oss"
  register: nexus

- name: Make manifest directory
  file:
    path: "/datadrive/export/nexus-oss"
    state: directory
    owner: "nobody"
    group: "nogroup"
    mode: '0777'
  when: nexus.stat.exists == False

- name: Check if Nexus OSS data exists
  stat:
    path: "/datadrive/export/nexus-oss/data"
  register: nexus_data

- name: Make manifest directory
  file:
    path: "/datadrive/export/nexus-oss/data"
    state: directory
    owner: "nobody"
    group: "nogroup"
    mode: '0777'
  when: nexus_data.stat.exists == False

- name: Check if Nexus OSS blob store exists
  stat:
    path: "/datadrive/export/nexus-oss/blobs"
  register: nexus_blob

- name: Make manifest directory
  file:
    path: "/datadrive/export/nexus-oss/blobs"
    state: directory
    owner: "nobody"
    group: "nogroup"
    mode: '0777'
  when: nexus_blob.stat.exists == False

- name: Check if Nexus OSS user root exists
  stat:
    path: "/datadrive/export/nexus-oss/user-root"
  register: nexus_user_root

- name: Make manifest directory
  file:
    path: "/datadrive/export/nexus-oss/user-root"
    state: directory
    owner: "nobody"
    group: "nogroup"
    mode: '0777'
  when: nexus_user_root.stat.exists == False

- name: Copy manifest
  copy:
    src: k8s_nexus_oss/manifests/
    dest: "/home/{{ admin }}/k8s/nexus_oss"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False

- name: Copy templated ingress
  template:
    src: k8s_nexus_oss/manifests/ingress.yaml
    dest: "/home/{{ admin }}/k8s/nexus_oss"
    owner: "{{ admin }}"

- name: Create data PV
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/data-pv.yaml

- name: Create blobs PV
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/blobs-pv.yaml

- name: Create user-root PV
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/user-root-pv.yaml

- name: Create data PVC
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/data-pvc.yaml

- name: Create blobs PVC
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/blobs-pvc.yaml

- name: Create user-root PVC
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/user-root-pvc.yaml

- name: Create Nexus OSS deployment
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/deploy.yaml

- name: Create Nexus OSS service
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/service.yaml

- name: Create Nexus OSS Docker services
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/docker-service.yaml

- name: Create Nexus OSS ingress
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/ingress.yaml
