#!/bin/bash
# -------------------------------------------------------------------
#
# Module:         k8s-terraform
# Submodule:      templates/config
# Environments:   all
# Purpose:        A template ssh configuration file which is copied
#                 to each node.
#
# Created on:     23 June 2019
# Created by:     David Sanders
# Creator email:  dsanderscanada@nospam-gmail.com
#
# -------------------------------------------------------------------
# Modifed On   | Modified By                 | Release Notes
# -------------------------------------------------------------------
# 23 Jun 2019  | David Sanders               | First release.
# -------------------------------------------------------------------
Host *
  StrictHostKeyChecking no
  IdentitiesOnly yes
  IdentityFile ~/.ssh/azure_pk
  ForwardAgent no
