- name: Check if Nexus OSS NFS Share exists
  stat:
    path: "/datadrive/export/nexus-oss"
  register: nexus

- name: Make manifest directory
  file:
    path: "/datadrive/export/nexus-oss"
    state: directory
    owner: "nobody"
    group: "nogroup"
    mode: '0777'
  when: nexus.stat.exists == False

- name: Check if Nexus OSS data exists
  stat:
    path: "/datadrive/export/nexus-oss/data"
  register: nexus_data

- name: Make manifest directory
  file:
    path: "/datadrive/export/nexus-oss/data"
    state: directory
    owner: "nobody"
    group: "nogroup"
    mode: '0777'
  when: nexus_data.stat.exists == False

- name: Check if Nexus OSS blob store exists
  stat:
    path: "/datadrive/export/nexus-oss/blobs"
  register: nexus_blob

- name: Make manifest directory
  file:
    path: "/datadrive/export/nexus-oss/blobs"
    state: directory
    owner: "nobody"
    group: "nogroup"
    mode: '0777'
  when: nexus_blob.stat.exists == False

- name: Check if Nexus OSS user root exists
  stat:
    path: "/datadrive/export/nexus-oss/user-root"
  register: nexus_user_root

- name: Make manifest directory
  file:
    path: "/datadrive/export/nexus-oss/user-root"
    state: directory
    owner: "nobody"
    group: "nogroup"
    mode: '0777'
  when: nexus_user_root.stat.exists == False

- name: Check manifest exists
  stat:
    path: "/home/{{ admin }}/k8s/nexus_oss"
  register: manifests

- name: Copy manifest
  copy:
    src: app_nexus_oss/manifests/
    dest: "/home/{{ admin }}/k8s/nexus_oss"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False

- name: Copy templated ingress (TLS - Production)
  template:
    src: app_nexus_oss/manifests/ingress.yaml
    dest: "/home/{{ admin }}/k8s/nexus_oss"
    owner: "{{ admin }}"
  when: manifests.stat.exists == False

- name: Create Persistent Volumes
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/data-pv.yaml
    sleep 2
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/blobs-pv.yaml
    sleep 2
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/user-root-pv.yaml

- name: Create Persistent Volume Claims
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/data-pvc.yaml
    sleep 2
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/blobs-pvc.yaml
    sleep 2
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/user-root-pvc.yaml

- name: Create Nexus deployment
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/deploy.yaml

- name: Create Nexus services
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/service.yaml
    sleep 2
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/docker-service.yaml

- name: Create Nexus ingress
  shell: |
    kubectl apply -f /home/{{ admin }}/k8s/nexus_oss/ingress.yaml

- name: Fetch credentials (if exist)
  shell: kubectl get secret regcreds
  register: docker_registry_secret
  ignore_errors: yes

- name: Create nexus credentials (pre-defined) in regcreds
  shell: |
    kubectl create secret docker-registry regcreds --docker-server=http://{{ registry }} --docker-username={{ nexus_username }} --docker-password="{{ nexus_password }}"
  when: docker_registry_secret.stdout == ""
