# - name: Sleep for 30s to enable workers to ready
#   pause:
#     seconds: 30

- name: Label worker 1
  shell: |
    echo "Adding label worker to {{ worker_1|lower }}"
    kubectl label node {{ worker_1|lower }} role=worker
    echo "Adding label worker to {{ worker_2|lower }}"
    kubectl label node {{ worker_2|lower }} role=worker
    echo "Adding label master to {{ master|lower }}"
    kubectl label node {{ master|lower }} role=master
  ignore_errors: yes
